// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYELR2FfY0IwyeP-VgP-aB4uQbvt78Po',
    appId: '1:707314906020:web:402968f554013e455d0731',
    messagingSenderId: '707314906020',
    projectId: 'ulearning-app-8f5a0',
    authDomain: 'ulearning-app-8f5a0.firebaseapp.com',
    storageBucket: 'ulearning-app-8f5a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pOsHAY8VvIBS-k_MnSjbttUoduR7t3g',
    appId: '1:707314906020:android:ae302413da1820ee5d0731',
    messagingSenderId: '707314906020',
    projectId: 'ulearning-app-8f5a0',
    storageBucket: 'ulearning-app-8f5a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKt_JJFpQdMRsjgf801IEPK0yJi5xMcZ0',
    appId: '1:707314906020:ios:308fdf0b7ef052665d0731',
    messagingSenderId: '707314906020',
    projectId: 'ulearning-app-8f5a0',
    storageBucket: 'ulearning-app-8f5a0.appspot.com',
    iosBundleId: 'com.example.ulearnBlocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKt_JJFpQdMRsjgf801IEPK0yJi5xMcZ0',
    appId: '1:707314906020:ios:6ddeb067832cb1b15d0731',
    messagingSenderId: '707314906020',
    projectId: 'ulearning-app-8f5a0',
    storageBucket: 'ulearning-app-8f5a0.appspot.com',
    iosBundleId: 'com.example.ulearnBlocApp.RunnerTests',
  );
}
